//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.01 at 05:49:54 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap-service/clients", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap_service.clients;
