//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.01 at 05:49:54 PM YEKT 
//


package soap_service.applications;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap_service.applications package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap_service.applications
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetApplicationByIdRequest }
     * 
     */
    public GetApplicationByIdRequest createGetApplicationByIdRequest() {
        return new GetApplicationByIdRequest();
    }

    /**
     * Create an instance of {@link GetApplicationByIdResponse }
     * 
     */
    public GetApplicationByIdResponse createGetApplicationByIdResponse() {
        return new GetApplicationByIdResponse();
    }

    /**
     * Create an instance of {@link ApplicationInfo }
     * 
     */
    public ApplicationInfo createApplicationInfo() {
        return new ApplicationInfo();
    }

    /**
     * Create an instance of {@link GetAllApplicationsRequest }
     * 
     */
    public GetAllApplicationsRequest createGetAllApplicationsRequest() {
        return new GetAllApplicationsRequest();
    }

    /**
     * Create an instance of {@link GetAllApplicationsResponse }
     * 
     */
    public GetAllApplicationsResponse createGetAllApplicationsResponse() {
        return new GetAllApplicationsResponse();
    }

    /**
     * Create an instance of {@link AddApplicationRequest }
     * 
     */
    public AddApplicationRequest createAddApplicationRequest() {
        return new AddApplicationRequest();
    }

    /**
     * Create an instance of {@link AddApplicationResponse }
     * 
     */
    public AddApplicationResponse createAddApplicationResponse() {
        return new AddApplicationResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UpdateApplicationRequest }
     * 
     */
    public UpdateApplicationRequest createUpdateApplicationRequest() {
        return new UpdateApplicationRequest();
    }

    /**
     * Create an instance of {@link UpdateApplicationResponse }
     * 
     */
    public UpdateApplicationResponse createUpdateApplicationResponse() {
        return new UpdateApplicationResponse();
    }

    /**
     * Create an instance of {@link DeleteApplicationRequest }
     * 
     */
    public DeleteApplicationRequest createDeleteApplicationRequest() {
        return new DeleteApplicationRequest();
    }

    /**
     * Create an instance of {@link DeleteApplicationResponse }
     * 
     */
    public DeleteApplicationResponse createDeleteApplicationResponse() {
        return new DeleteApplicationResponse();
    }

}
