//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.01 at 05:49:54 PM YEKT 
//


package soap_service.services;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap_service.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap_service.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetServiceByIdRequest }
     * 
     */
    public GetServiceByIdRequest createGetServiceByIdRequest() {
        return new GetServiceByIdRequest();
    }

    /**
     * Create an instance of {@link GetServiceByIdResponse }
     * 
     */
    public GetServiceByIdResponse createGetServiceByIdResponse() {
        return new GetServiceByIdResponse();
    }

    /**
     * Create an instance of {@link ServiceInfo }
     * 
     */
    public ServiceInfo createServiceInfo() {
        return new ServiceInfo();
    }

    /**
     * Create an instance of {@link GetAllServicesRequest }
     * 
     */
    public GetAllServicesRequest createGetAllServicesRequest() {
        return new GetAllServicesRequest();
    }

    /**
     * Create an instance of {@link GetAllServicesResponse }
     * 
     */
    public GetAllServicesResponse createGetAllServicesResponse() {
        return new GetAllServicesResponse();
    }

    /**
     * Create an instance of {@link AddServiceRequest }
     * 
     */
    public AddServiceRequest createAddServiceRequest() {
        return new AddServiceRequest();
    }

    /**
     * Create an instance of {@link AddServiceResponse }
     * 
     */
    public AddServiceResponse createAddServiceResponse() {
        return new AddServiceResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UpdateServiceRequest }
     * 
     */
    public UpdateServiceRequest createUpdateServiceRequest() {
        return new UpdateServiceRequest();
    }

    /**
     * Create an instance of {@link UpdateServiceResponse }
     * 
     */
    public UpdateServiceResponse createUpdateServiceResponse() {
        return new UpdateServiceResponse();
    }

    /**
     * Create an instance of {@link DeleteServiceRequest }
     * 
     */
    public DeleteServiceRequest createDeleteServiceRequest() {
        return new DeleteServiceRequest();
    }

    /**
     * Create an instance of {@link DeleteServiceResponse }
     * 
     */
    public DeleteServiceResponse createDeleteServiceResponse() {
        return new DeleteServiceResponse();
    }

}
